const labScenarios = {
  timeout:{id:'lab_timeout',amount:12499,error_description:'issuer network timeout after OTP',customer_opted_in:true,retry_count:0},
  funds:{id:'lab_funds',amount:8999,error_description:'insufficient balance',customer_opted_in:true,retry_count:0},
  duplicate:{id:'lab_duplicate',amount:7800,duplicate_suspected:true,customer_opted_in:true,retry_count:0},
  consent:{id:'lab_consent',amount:6500,error_description:'insufficient balance',customer_opted_in:false,retry_count:0},
  retry:{id:'lab_retry',amount:11999,error_description:'issuer timeout',customer_opted_in:true,retry_count:1}
};
const seedCases = [
  {id:'pay_Q8L2', customer:'Mira Patel', amount:12499, cause:'Bank timeout after OTP', confidence:94, action:'Retry at 09:30 + WhatsApp link', status:'approve', evidence:'Issuer timeout · previous successful UPI payments · customer still active'},
  {id:'pay_F6R9', customer:'Aarav Mehta', amount:8999, cause:'Insufficient balance', confidence:89, action:'Send salary-day retry link', status:'approve', evidence:'NSF response · payday is tomorrow · consent is active'},
  {id:'pay_B4K1', customer:'Studio Nila', amount:45000, cause:'Invoice overdue, 14 days', confidence:96, action:'Escalate to accounts owner', status:'approve', evidence:'B2B invoice · two reminders opened · no dispute flag'},
  {id:'pay_Z2P7', customer:'Kabir Shah', amount:2499, cause:'Checkout abandonment', confidence:77, action:'Send one cart reminder', status:'approve', evidence:'Cart open 8 mins · viewed shipping · opted in'},
  {id:'pay_J1M5', customer:'Kavya Iyer', amount:11999, cause:'Repeated mandate failure', confidence:92, action:'Hold — consent refresh needed', status:'hold', evidence:'3 failures in 24h · retry limit reached'},
  {id:'pay_H7V3', customer:'Nora Collective', amount:7800, cause:'Possible duplicate charge', confidence:61, action:'Hold — human review', status:'hold', evidence:'Duplicate fingerprint · low diagnostic confidence'},
];
let cases = structuredClone(seedCases), audit = [], filter = 'all', activeCase = null;
const rupees = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const $ = id => document.getElementById(id);
function totals(){const risk=cases.reduce((a,c)=>a+c.amount,0);const approved=cases.filter(c=>c.outcome==='recovered');const recovered=approved.reduce((a,c)=>a+c.amount,0);const gates=cases.filter(c=>c.status==='approve'&&!c.outcome).length;const avg=Math.round(cases.filter(c=>c.status==='approve').reduce((a,c)=>a+c.confidence,0)/cases.filter(c=>c.status==='approve').length);return{risk,recovered,gates,avg,approved};}
function renderMetrics(){const t=totals();$('atRisk').textContent=rupees(t.risk);$('batchInfo').textContent=`across ${cases.length + 54} payment events`; $('recovered').textContent=rupees(t.recovered);$('recoveryRate').textContent=`${Math.round(t.recovered/t.risk*100)||0}%`; $('gated').textContent=t.gates;$('confidence').textContent=`${t.avg||0}%`; $('queueBadge').textContent=t.gates; $('detected').textContent=cases.length+54;$('diagnosed').textContent=cases.length;$('bounded').textContent=cases.filter(c=>c.status==='approve').length;$('recoveredCount').textContent=t.approved.length;}
function renderCases(){const shown=cases.filter(c=>filter==='all'||c.status===filter);$('caseRows').innerHTML=shown.map(c=>`<tr><td><span class="customer">${c.customer}</span><span class="payment">${c.id}</span></td><td class="risk">${rupees(c.amount)}</td><td><span class="diagnosis">${c.cause}</span></td><td><span class="action">${c.outcome==='recovered'?'Recovered ✓':c.action}</span></td><td><span class="tag ${c.status}">${c.outcome==='recovered'?'COMPLETED':c.status==='approve'?'APPROVAL REQUIRED':'HELD BY POLICY'}</span></td><td><button class="secondary row-action" data-details="${c.id}">Case file</button>${c.status==='approve'&&!c.outcome?` <button class="secondary row-action" data-case="${c.id}">Review</button>`:''}</td></tr>`).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>openApproval(b.dataset.case));document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>openCaseFile(b.dataset.details));}
function renderAudit(){ $('auditLog').innerHTML=audit.length?audit.map(a=>`<div class="audit-item"><div><strong>${a.title}</strong><p>${a.detail}</p></div><time>${a.time}</time></div>`).join(''):'<p class="empty">No sweep has been run. Every decision will appear here with evidence, policy status, and outcome.</p>';}
function renderInsight(){const counts={Timeout:2, 'Insufficient balance':1, Invoice:1, Abandonment:1, Mandate:1};const max=2;$('miniBars').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="bar ${v===max?'active':''}" style="height:${25+v*16}px"><span>${k.split(' ')[0]}</span></div>`).join('');$('topDriver').textContent='Bank timeout after OTP';$('driverText').textContent='Timeouts are the largest recoverable loss driver. The agent recommends one delayed retry only where customer intent and issuer signals support it.';$('evidenceCoverage').textContent='100%';}
function sweep(){audit=[];cases.forEach(c=>audit.push({title:`Diagnosed ${c.id}: ${c.cause}`,detail:`Evidence: ${c.evidence}. Policy outcome: ${c.status==='approve'?'eligible for human approval':'held; no money action permitted'}.`,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}));$('engineState').textContent='SWEEP COMPLETE';$('engineState').style.background='#e7f5ed';renderAll();renderInsight();}
function openApproval(id){activeCase=cases.find(c=>c.id===id);$('approvalContent').innerHTML=`<div class="dialog-case"><strong>${activeCase.customer} · ${rupees(activeCase.amount)}</strong><br>${activeCase.action}<br><br><span class="eyebrow">EVIDENCE</span><br>${activeCase.evidence}<br><br><span class="eyebrow">BOUNDARY</span><br>One action only. Automatic retries and further customer contact remain disabled.</div>`;$('approvalDialog').showModal();}
function caseEvent(c){const lookup={'Bank timeout after OTP':'issuer network timeout','Insufficient balance':'insufficient balance','Invoice overdue, 14 days':'insufficient balance','Checkout abandonment':'checkout abandoned','Repeated mandate failure':'mandate expired','Possible duplicate charge':'duplicate payment'};return{id:c.id,amount:c.amount*100,error_description:lookup[c.cause]||'unclassified error',customer_opted_in:c.status==='approve',retry_count:c.cause==='Repeated mandate failure'?1:0,duplicate_suspected:c.cause==='Possible duplicate charge',checkout_open_minutes:c.cause==='Checkout abandonment'?8:0};}
function openCaseFile(id){const c=cases.find(x=>x.id===id);const confidence=c.confidence?'AI confidence · '+c.confidence+'%':'Policy hold';const policy=c.outcome==='recovered'?'Approved and completed':c.status==='approve'?'Human approval required':'Hard stop — no action';const draftTools=c.status==='approve'?'<div class="case-field"><span>CONSENT-SAFE MESSAGE DRAFT</span><b>Preview only — no message is sent.</b><div class="message-tools"><button type="button" class="secondary" data-language="en">Draft English</button><button type="button" class="secondary" data-language="hinglish">Draft Hinglish</button></div><div class="message-output" id="messageOutput"></div></div>':'';$('caseTitle').textContent=`${c.customer} · ${c.id}`;$('caseContent').innerHTML=`<div class="case-summary"><div><strong>${c.cause}</strong><small>${confidence}</small></div><span class="case-amount">${rupees(c.amount)}</span></div><div class="case-grid"><div class="case-field"><span>RECOMMENDED ACTION</span><b>${c.outcome==='recovered'?'Recovered ✓':c.action}</b></div><div class="case-field"><span>POLICY DECISION</span><b>${policy}</b></div></div><div class="case-field"><span>EVIDENCE USED</span><ul class="evidence-list">${c.evidence.split(' · ').map(e=>`<li>${e}</li>`).join('')}</ul></div>${draftTools}<div class="timeline"><h3>Recovery timeline</h3><div class="timeline-item"><span>T+00:00</span>Payment event entered the recovery queue.</div><div class="timeline-item"><span>T+00:01</span>Diagnosis completed: ${c.cause}.</div><div class="timeline-item"><span>T+00:01</span>${c.status==='approve'?'Policy allowed one bounded action and requested human approval.':'Policy stopped the workflow and kept the exception visible.'}</div>${c.outcome?'<div class="timeline-item"><span>T+00:03</span>Human approval recorded; outcome measured as recovered in this demo.</div>':''}</div><div class="case-dialog-footer">${c.status==='approve'&&!c.outcome?`<button type="button" class="primary" id="reviewFromFile">Review action <span>→</span></button>`:'<button value="cancel" class="secondary">Close case file</button>'}</div>`;$('caseDialog').showModal();const review=$('reviewFromFile');if(review)review.onclick=()=>{$('caseDialog').close();openApproval(c.id);};document.querySelectorAll('[data-language]').forEach(button=>button.onclick=()=>draftMessage(c,button.dataset.language));}
async function draftMessage(c,language){const output=$('messageOutput');output.classList.add('visible');output.textContent='Creating policy-safe preview…';try{const response=await fetch('/api/draft-message',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event:caseEvent(c),language})});const data=await response.json();if(!response.ok)throw new Error(data.reason||'Draft unavailable');output.innerHTML=`${data.message.replace('[PAYMENT_LINK]','[secure payment link]')}<small>Draft only. Human approval and an explicit send step are still required.</small>`;}catch(error){output.innerHTML='Start RecoverFlow with <code>npm run dev</code> to generate the server-validated message preview.';}}
function renderAll(){renderMetrics();renderCases();renderAudit();}
$('runButton').onclick=sweep;$('resetButton').onclick=()=>{cases=structuredClone(seedCases);audit=[];$('engineState').textContent='READY';renderAll();$('topDriver').textContent='—';$('driverText').textContent='Run a sweep to see a decision-ready explanation.';$('miniBars').innerHTML='';$('evidenceCoverage').textContent='0%';};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('selected',x===b));renderCases();});
$('approvalDialog').addEventListener('close',()=>{if($('approvalDialog').returnValue==='approve'&&activeCase){activeCase.outcome='recovered';audit.unshift({title:`Approved and recovered ${activeCase.id}`,detail:`Human approved “${activeCase.action}”. Outcome recorded as recovered for demo simulation. Full evidence and policy boundary retained.`,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});renderAll();}activeCase=null;});
$('downloadButton').onclick=()=>{const blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),cases,audit,policy:'One action per 24h; explicit approval required; contact opt-outs enforced.'},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='recoverflow-audit.json';a.click();URL.revokeObjectURL(a.href);};
async function evaluateLab(){const button=$('evaluateButton'), result=$('decisionResult');button.disabled=true;button.textContent='Evaluating…';result.innerHTML='<span class="result-muted">Evaluating evidence and policy…</span>';try{const event=labScenarios[$('scenarioSelect').value];const response=await fetch('/api/diagnose',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(event)});const data=await response.json();if(!response.ok)throw new Error(data.error||'service unavailable');const pct=Math.round(data.diagnosis.confidence*100);const allowed=data.decision.status==='approval_required';result.innerHTML=`<strong class="${allowed?'result-ok':'result-hold'}">${allowed?'APPROVAL REQUIRED':'HELD BY POLICY'} · ${data.decision.policy_code}</strong><br>Diagnosis: ${data.diagnosis.label.replaceAll('_',' ')} (${pct}% confidence). ${allowed?data.diagnosis.recommended_action:data.decision.reason}`;}catch(error){result.innerHTML='<span class="result-hold">Start RecoverFlow with <code>npm run dev</code> to use the live decision service.</span>';}finally{button.disabled=false;button.innerHTML='Evaluate event <span>→</span>';}}
$('evaluateButton').onclick=evaluateLab;
function simulateBatch(){const volume=Number($('volumeSelect').value), averageAtRisk=8600, recoverableShare=.72;const atRisk=volume*averageAtRisk, genericRecovered=Math.round(atRisk*recoverableShare*.31), rfRecovered=Math.round(atRisk*recoverableShare*.52), genericWaste=Math.round(volume*.28), protectedCases=Math.round(volume*.28), genericReviews=Math.round(volume*.64), rfReviews=Math.round(volume*.37);$('genericRecovered').textContent=rupees(genericRecovered);$('genericWaste').textContent=`${genericWaste} actions`;$('genericReviews').textContent=`${genericReviews} cases`;$('rfRecovered').textContent=rupees(rfRecovered);$('rfProtected').textContent=`${protectedCases} cases`;$('rfReviews').textContent=`${rfReviews} cases`;const difference=rfRecovered-genericRecovered;$('simInsight').innerHTML=`<span>ⓘ</span><p><strong>Scenario result:</strong> RecoverFlow recovers <strong>${rupees(difference)}</strong> more from this ${volume}-event synthetic batch while holding ${protectedCases} unsafe or low-signal cases. Assumptions: ₹${averageAtRisk.toLocaleString('en-IN')} average at-risk value, 72% recoverable events, and a one-action policy. This is a reproducible demo model—not a live merchant performance claim.</p>`;}
$('simulateButton').onclick=simulateBatch;
renderAll();
